// <auto-generated />
using System;
using HomeHavenAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeHavenAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240520182847_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeHavenAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Villa"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Lägenhet"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "RadHus"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "FritidsBoende"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Tomt"
                        });
                });

            modelBuilder.Entity("HomeHavenAPI.Models.FirmRequest", b =>
                {
                    b.Property<int>("FirmRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmRequestId"));

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RealtorFirmId")
                        .HasColumnType("int");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FirmRequestId");

                    b.ToTable("FirmRequests");
                });

            modelBuilder.Entity("HomeHavenAPI.Models.Realtor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RealtorFirmId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RealtorFirmId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ac31313d-d278-43d9-a72d-39fc96dc2e92",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5b2c55da-3662-4b57-9088-1df86cc710ff",
                            Email = "sofia.andersson@example.com",
                            EmailConfirmed = false,
                            FirstName = "Sofia",
                            LastName = "Andersson",
                            LockoutEnabled = false,
                            PhoneNumber = "070-1234567",
                            PhoneNumberConfirmed = false,
                            ProfilePictureURL = "https://www.feedingmatters.org/wp-content/uploads/2022/12/Generic-profile-pic.png",
                            RealtorFirmId = 2,
                            SecurityStamp = "b1587c61-83f5-4e74-b3d7-db7b6f024bbc",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "e8411d7f-4c81-4e1a-92fc-1890db0e5b81",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8191bdd-fd4a-4251-b66c-59234546190e",
                            Email = "erik.svensson@example.com",
                            EmailConfirmed = false,
                            FirstName = "Erik",
                            LastName = "Svensson",
                            LockoutEnabled = false,
                            PhoneNumber = "073-9876543",
                            PhoneNumberConfirmed = false,
                            ProfilePictureURL = "https://st3.depositphotos.com/4060975/17707/v/450/depositphotos_177073010-stock-illustration-male-vector-icon.jpg",
                            RealtorFirmId = 3,
                            SecurityStamp = "7a763fb4-2654-45a8-95e9-e834d766a9bf",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "60205c1a-ef79-44ac-89b2-ac75176e3408",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46d7623d-72ae-4c1e-a1fd-449361b15450",
                            Email = "emma.johansson@example.com",
                            EmailConfirmed = false,
                            FirstName = "Emma",
                            LastName = "Johansson",
                            LockoutEnabled = false,
                            PhoneNumber = "076-1112233",
                            PhoneNumberConfirmed = false,
                            RealtorFirmId = 2,
                            SecurityStamp = "dcefd990-982c-420b-b391-ae8927e3ccb6",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "9dcb614e-6280-4101-ae5a-875d51e33480",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a5df987-cb47-47a7-b82b-4823fa9797e0",
                            Email = "anders.karlsson@example.com",
                            EmailConfirmed = false,
                            FirstName = "Anders",
                            LastName = "Karlsson",
                            LockoutEnabled = false,
                            PhoneNumber = "072-5554441",
                            PhoneNumberConfirmed = false,
                            ProfilePictureURL = "https://www.creativefabrica.com/wp-content/uploads/2023/05/23/Bearded-man-avatar-Generic-male-profile-Graphics-70342414-1.png",
                            RealtorFirmId = 4,
                            SecurityStamp = "5b5f9e5e-47ba-4797-a103-8b891f7f18b9",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3869a014-937b-4970-9021-3bb704bb10a2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c285ee4-3d98-4894-a681-f27e3d3f9ec7",
                            Email = "linnea.lindgren@example.com",
                            EmailConfirmed = false,
                            FirstName = "Linnea",
                            LastName = "Lindgren",
                            LockoutEnabled = false,
                            PhoneNumber = "074-8889990",
                            PhoneNumberConfirmed = false,
                            RealtorFirmId = 5,
                            SecurityStamp = "ef9f1d1d-2dbd-4c1a-914b-9dbf4b01c805",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("HomeHavenAPI.Models.RealtorFirm", b =>
                {
                    b.Property<int?>("RealtorFirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("RealtorFirmId"));

                    b.Property<string>("Descrpition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealtorFirmId");

                    b.ToTable("Firms");

                    b.HasData(
                        new
                        {
                            RealtorFirmId = 1,
                            Descrpition = "Tillhör ej någon mäklarfirma",
                            FirmName = "Ingen",
                            LogoURL = "URL"
                        },
                        new
                        {
                            RealtorFirmId = 2,
                            Descrpition = "Specialiserade på lyxiga och exklusiva fastigheter, erbjuder Elite Properties en förstklassig service för kunder som söker det bästa av det bästa.",
                            FirmName = "Elite Properties",
                            LogoURL = "URL"
                        },
                        new
                        {
                            RealtorFirmId = 3,
                            Descrpition = "Med starka förbindelser och expertis inom fastighetsmarknaden, strävar Prime Real Estate Solutions efter att hjälpa kunder att hitta de mest lönsamma fastighetsaffärerna.",
                            FirmName = "Prime Real Estate Solutions",
                            LogoURL = "URL"
                        },
                        new
                        {
                            RealtorFirmId = 4,
                            Descrpition = "Fokuserar på att skapa en \"näste\" åt sina kunder där de kan känna sig hemma och bekväma i den stadsmiljö de älskar.",
                            FirmName = "Urban Nest Realty",
                            LogoURL = "URL"
                        },
                        new
                        {
                            RealtorFirmId = 5,
                            Descrpition = "Tar sina kunder till nya horisonter genom att guida dem genom köp- och säljprocessen med en personlig och professionell approach.",
                            FirmName = "Horizon Homes Real Estate",
                            LogoURL = "URL"
                        });
                });

            modelBuilder.Entity("HomeHavenAPI.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Township")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            County = "Stockholm",
                            Township = "Sollentuna"
                        },
                        new
                        {
                            RegionId = 2,
                            County = "Uppsala",
                            Township = "Östhammar"
                        },
                        new
                        {
                            RegionId = 3,
                            County = "Jönköpings",
                            Township = "Gislaved"
                        },
                        new
                        {
                            RegionId = 4,
                            County = "Kalmar",
                            Township = "Torsås"
                        },
                        new
                        {
                            RegionId = 5,
                            County = "Blekinge",
                            Township = "Karlskrona"
                        },
                        new
                        {
                            RegionId = 6,
                            County = "Västerbotten",
                            Township = "Umeå"
                        },
                        new
                        {
                            RegionId = 7,
                            County = "Stockholm",
                            Township = "Ekerö"
                        },
                        new
                        {
                            RegionId = 8,
                            County = "Jämtland",
                            Township = "Östersund"
                        },
                        new
                        {
                            RegionId = 9,
                            County = "Skåne",
                            Township = "Malmö"
                        },
                        new
                        {
                            RegionId = 10,
                            County = "Skåne",
                            Township = "Hörby"
                        },
                        new
                        {
                            RegionId = 12,
                            County = "Stockholm",
                            Township = "Järfälla"
                        },
                        new
                        {
                            RegionId = 14,
                            County = "Stockholm",
                            Township = "Botkyrka"
                        },
                        new
                        {
                            RegionId = 15,
                            County = "Stockholm",
                            Township = "Solna"
                        },
                        new
                        {
                            RegionId = 16,
                            County = "Stockholm",
                            Township = "Lidingö"
                        },
                        new
                        {
                            RegionId = 17,
                            County = "Uppsala",
                            Township = "Håbå"
                        },
                        new
                        {
                            RegionId = 19,
                            County = "Uppsala",
                            Township = "Knivsta"
                        },
                        new
                        {
                            RegionId = 20,
                            County = "Uppsala",
                            Township = "Enköping"
                        },
                        new
                        {
                            RegionId = 21,
                            County = "Uppsala",
                            Township = "Älvkarleby"
                        },
                        new
                        {
                            RegionId = 22,
                            County = "Uppsala",
                            Township = "Tierp"
                        },
                        new
                        {
                            RegionId = 23,
                            County = "Södermanland",
                            Township = "Vingåker"
                        },
                        new
                        {
                            RegionId = 24,
                            County = "Södermanland",
                            Township = "Gnesta"
                        },
                        new
                        {
                            RegionId = 25,
                            County = "Södermanland",
                            Township = "Nyköping"
                        },
                        new
                        {
                            RegionId = 26,
                            County = "Södermanland",
                            Township = "Oxelösund"
                        },
                        new
                        {
                            RegionId = 27,
                            County = "Södermanland",
                            Township = "Flen"
                        },
                        new
                        {
                            RegionId = 28,
                            County = "Södermanland",
                            Township = "Katrineholm"
                        },
                        new
                        {
                            RegionId = 29,
                            County = "Södermanland",
                            Township = "Eskilstuna"
                        },
                        new
                        {
                            RegionId = 30,
                            County = "Södermanland",
                            Township = "Strängnäs"
                        },
                        new
                        {
                            RegionId = 31,
                            County = "Södermanland",
                            Township = "Trosa"
                        },
                        new
                        {
                            RegionId = 32,
                            County = "Östergötland",
                            Township = "Ödeshög"
                        },
                        new
                        {
                            RegionId = 33,
                            County = "Östergötland",
                            Township = "Ydre"
                        },
                        new
                        {
                            RegionId = 34,
                            County = "Östergötland",
                            Township = "Kinda"
                        },
                        new
                        {
                            RegionId = 35,
                            County = "Östergötland",
                            Township = "Boxholm"
                        },
                        new
                        {
                            RegionId = 36,
                            County = "Östergötland",
                            Township = "Åtvidaberg"
                        },
                        new
                        {
                            RegionId = 37,
                            County = "Östergötland",
                            Township = "Finspång"
                        },
                        new
                        {
                            RegionId = 38,
                            County = "Östergötland",
                            Township = "Valdemarsvik"
                        },
                        new
                        {
                            RegionId = 39,
                            County = "Östergötland",
                            Township = "Linköping"
                        },
                        new
                        {
                            RegionId = 41,
                            County = "Östergötland",
                            Township = "Norrköping"
                        },
                        new
                        {
                            RegionId = 42,
                            County = "Östergötland",
                            Township = "Söderköping"
                        },
                        new
                        {
                            RegionId = 43,
                            County = "Östergötland",
                            Township = "Motala"
                        },
                        new
                        {
                            RegionId = 44,
                            County = "Östergötland",
                            Township = "Vadstena"
                        },
                        new
                        {
                            RegionId = 45,
                            County = "Östergötland",
                            Township = "Mjölby"
                        },
                        new
                        {
                            RegionId = 46,
                            County = "Jönköping",
                            Township = "Aneby"
                        },
                        new
                        {
                            RegionId = 47,
                            County = "Jönköping",
                            Township = "Gnosjö"
                        },
                        new
                        {
                            RegionId = 48,
                            County = "Jönköping",
                            Township = "Mullsjö"
                        },
                        new
                        {
                            RegionId = 49,
                            County = "Jönköping",
                            Township = "Habo"
                        },
                        new
                        {
                            RegionId = 51,
                            County = "Jönköping",
                            Township = "Vaggeryd"
                        },
                        new
                        {
                            RegionId = 52,
                            County = "Jönköping",
                            Township = "Jönköping"
                        },
                        new
                        {
                            RegionId = 53,
                            County = "Jönköping",
                            Township = "Nässjö"
                        },
                        new
                        {
                            RegionId = 55,
                            County = "Jönköping",
                            Township = "Sävsjö"
                        },
                        new
                        {
                            RegionId = 56,
                            County = "Jönköping",
                            Township = "Vetlanda"
                        },
                        new
                        {
                            RegionId = 57,
                            County = "Jönköping",
                            Township = "Eksjö"
                        },
                        new
                        {
                            RegionId = 58,
                            County = "Jönköping",
                            Township = "Tranås"
                        },
                        new
                        {
                            RegionId = 59,
                            County = "Kronoberg",
                            Township = "Uppvidinge"
                        },
                        new
                        {
                            RegionId = 60,
                            County = "Kronoberg",
                            Township = "Lessebo"
                        },
                        new
                        {
                            RegionId = 61,
                            County = "Kronoberg",
                            Township = "Tingsryd"
                        },
                        new
                        {
                            RegionId = 62,
                            County = "Kronoberg",
                            Township = "Alvesta"
                        },
                        new
                        {
                            RegionId = 63,
                            County = "Kronoberg",
                            Township = "Älmhult"
                        },
                        new
                        {
                            RegionId = 64,
                            County = "Kronoberg",
                            Township = "Markaryd"
                        },
                        new
                        {
                            RegionId = 65,
                            County = "Kronoberg",
                            Township = "Växsjö"
                        },
                        new
                        {
                            RegionId = 66,
                            County = "Kronoberg",
                            Township = "Ljungby"
                        },
                        new
                        {
                            RegionId = 67,
                            County = "Kalmar",
                            Township = "Högsby"
                        },
                        new
                        {
                            RegionId = 68,
                            County = "Uppsala",
                            Township = "Heby"
                        },
                        new
                        {
                            RegionId = 69,
                            County = "Uppsala",
                            Township = "Uppsala"
                        },
                        new
                        {
                            RegionId = 70,
                            County = "Kalmar",
                            Township = "Mörbylånga"
                        },
                        new
                        {
                            RegionId = 71,
                            County = "Kalmar",
                            Township = "Hultsfred"
                        },
                        new
                        {
                            RegionId = 72,
                            County = "Kalmar",
                            Township = "Mönsterås"
                        },
                        new
                        {
                            RegionId = 73,
                            County = "Kalmar",
                            Township = "Emmaboda"
                        },
                        new
                        {
                            RegionId = 74,
                            County = "Kalmar",
                            Township = "Kalmar"
                        },
                        new
                        {
                            RegionId = 75,
                            County = "Kalmar",
                            Township = "Nybro"
                        },
                        new
                        {
                            RegionId = 76,
                            County = "Kalmar",
                            Township = "Oskarshamn"
                        },
                        new
                        {
                            RegionId = 77,
                            County = "Kalmar",
                            Township = "Västervik"
                        },
                        new
                        {
                            RegionId = 78,
                            County = "Kalmar",
                            Township = "Vimmerby"
                        },
                        new
                        {
                            RegionId = 79,
                            County = "Kalmar",
                            Township = "Borgholm"
                        },
                        new
                        {
                            RegionId = 80,
                            County = "Gotland",
                            Township = "Gotland"
                        },
                        new
                        {
                            RegionId = 81,
                            County = "Blekinge",
                            Township = "Olofström"
                        },
                        new
                        {
                            RegionId = 82,
                            County = "Blekinge",
                            Township = "Ronneby"
                        },
                        new
                        {
                            RegionId = 83,
                            County = "Blekinge",
                            Township = "Karlshamn"
                        },
                        new
                        {
                            RegionId = 84,
                            County = "Blekinge",
                            Township = "Sölvesborg"
                        });
                });

            modelBuilder.Entity("HomeHavenAPI.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidenceId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BiArea")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ConstructionYear")
                        .HasColumnType("int");

                    b.Property<int>("LandArea")
                        .HasColumnType("int");

                    b.Property<int>("LivingArea")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyFee")
                        .HasColumnType("int");

                    b.Property<int>("OperatingCost")
                        .HasColumnType("int");

                    b.Property<string>("PictureListURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealtorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("ResidenceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.Property<int>("StartingPrice")
                        .HasColumnType("int");

                    b.HasKey("ResidenceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RealtorId");

                    b.HasIndex("RegionId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 1,
                            Address = "Sveavägen 42",
                            BiArea = 20,
                            CategoryId = 1,
                            ConstructionYear = 2004,
                            LandArea = 500,
                            LivingArea = 120,
                            MonthlyFee = 4000,
                            OperatingCost = 50000,
                            PictureListURL = "[\"https://gotenehus.se/app/uploads/2022/09/puff-vassholm-lada-1344x896.jpg\",\"https://cdn.decoist.com/wp-content/uploads/2014/08/Indoor-blossoms-in-a-modern-living-room.jpg\",\"https://homejab.com/wp-content/uploads/2021/11/https-__realtor.homejab.com_wp-content_uploads_2021_10_1906_Santa_Clara_Ave__Alameda__CA_94501__USA-20210131235707.jpg\"]",
                            RealtorId = "ac31313d-d278-43d9-a72d-39fc96dc2e92",
                            RegionId = 1,
                            ResidenceDescription = "Letar du efter en villa där du kan flytta rakt in utan att behöva renovera? \r\nDå ska du spana in denna trevliga 2-plansvilla som har genomgått en totalrenovering de senaste åren. Belägen på den generösa hörntomten erbjuds utrymme för odling, avkoppling och umgänge med familj och vänner på uteplatser i flera vädersträck. \r\nNjut av bekvämligheter som fjärrvärme, fiber och en carport som skyddar bilen mot väder och vind.\r\nVillan är besiktigad och besiktningsprotokollet finner du bilagt i annonsen.\r\nTa chansen att uppleva detta trevliga hus - välkommen att boka dig på visning!",
                            RoomCount = 5,
                            StartingPrice = 2000000
                        },
                        new
                        {
                            ResidenceId = 2,
                            Address = "Storgatan 12",
                            BiArea = 30,
                            CategoryId = 1,
                            ConstructionYear = 2000,
                            LandArea = 0,
                            LivingArea = 100,
                            MonthlyFee = 6500,
                            OperatingCost = 24500,
                            PictureListURL = "[\"https://bilder.hemnet.se/images/1024x/6d/e1/6de128c921bb2a0995de33a177fd7bdb.jpg\",\"https://bilder.hemnet.se/images/1024x/ba/02/ba0287abadb206747f13f9dce44ae0da.jpg\",\"https://bilder.hemnet.se/images/1024x/ce/55/ce55b3f6d283f55579312a806f02c0f8.jpg\",\"https://bilder.hemnet.se/images/1024x/dd/57/dd578b3d87879ecdb89fa2a4e0fdfd27.jpg\",\"https://bilder.hemnet.se/images/1024x/15/ef/15efb48083ba66b6dc1a5395b1b8cd8d.jpg\"]",
                            RealtorId = "e8411d7f-4c81-4e1a-92fc-1890db0e5b81",
                            RegionId = 2,
                            ResidenceDescription = "Letar du efter en villa där du kan flytta rakt in utan att behöva renovera? \r\nDå ska du spana in denna trevliga 2-plansvilla som har genomgått en totalrenovering de senaste åren. Belägen på den generösa hörntomten erbjuds utrymme för odling, avkoppling och umgänge med familj och vänner på uteplatser i flera vädersträck. \r\nNjut av bekvämligheter som fjärrvärme, fiber och en carport som skyddar bilen mot väder och vind.\r\nVillan är besiktigad och besiktningsprotokollet finner du bilagt i annonsen.\r\nTa chansen att uppleva detta trevliga hus - välkommen att boka dig på visning!",
                            RoomCount = 3,
                            StartingPrice = 1250000
                        },
                        new
                        {
                            ResidenceId = 3,
                            Address = "Strandvägen 7",
                            BiArea = 0,
                            CategoryId = 2,
                            ConstructionYear = 2018,
                            LandArea = 1000,
                            LivingArea = 250,
                            MonthlyFee = 4250,
                            OperatingCost = 32400,
                            PictureListURL = "[\"https://bilder.hemnet.se/images/1024x/82/ef/82ef5b32d254189c566c4bb6e16139ba.jpg\",\"https://bilder.hemnet.se/images/1024x/03/a3/03a35f482b889f513c3303b5f8d32c47.jpg\",\"https://bilder.hemnet.se/images/1024x/09/ba/09ba42eac3e24be70df9ccfd0234f4b9.jpg\",\"https://bilder.hemnet.se/images/1024x/52/dc/52dc234a8326652e1c451dff24c5977d.jpg\",\"https://bilder.hemnet.se/images/1024x/81/1b/811bda81e4c8832f78b9f8450ba25a79.jpg\"]",
                            RealtorId = "e8411d7f-4c81-4e1a-92fc-1890db0e5b81",
                            RegionId = 3,
                            ResidenceDescription = "Välkommen till denna trevliga bostadsrätt belägen i Riksbyggen Brf Björket i Kristianstad. Med en boyta på 84 kvadratmeter erbjuds här ett hem med två sovrum, rymligt vardagsrum, kök och matplats samt ett härligt inglasat uterum där man kan tillbringa många härliga dagar. Föreningen erbjuder trygghet och gemenskap samtidigt som man har närhet till stadens puls och service.\r\nBoendet på våningsplan ett passar perfekt för den som önskar ett lättillgängligt  boende med närhet till grönområden och promenadstråk i björket. \r\nVälkomna att kontakta mäklaren vid intresse! ",
                            RoomCount = 6,
                            StartingPrice = 3000000
                        },
                        new
                        {
                            ResidenceId = 4,
                            Address = "Norra Vallgatan 14",
                            BiArea = 15,
                            CategoryId = 3,
                            ConstructionYear = 2009,
                            LandArea = 625,
                            LivingArea = 130,
                            MonthlyFee = 7000,
                            OperatingCost = 31500,
                            PictureListURL = "[\"https://bilder.hemnet.se/images/1024x/0c/a5/0ca567fe6f8edeab861615c89e193fb1.jpg\",\"https://bilder.hemnet.se/images/1024x/3a/8c/3a8cbdbe3459c82fabadf2300dac4892.jpg\",\"https://bilder.hemnet.se/images/1024x/59/ce/59ce80115fc1db27b1bb69e0c332d650.jpg\",\"https://bilder.hemnet.se/images/1024x/53/d1/53d1e3f8cc5663a224a6df69f1f6bc67.jpg\"]",
                            RealtorId = "ac31313d-d278-43d9-a72d-39fc96dc2e92",
                            RegionId = 2,
                            ResidenceDescription = "Välkommen till Alfabetsvägen 52 och ett mycket tilltalande radhus i barnvänligt och populärt område! Entréplan rymmer ett stort kök med matplats, ett lättmöblerat vardagsrum, rymligt sovrum, modernt badrum med bastu och en praktisk tvättstuga. Ovanvåningen huserar fyra bra planerade sovrum och ett helkaklat badrum. Både fram- och baksida har härliga uteplatser med gott om utrymme för både loungemöbler och matmöblemang. Gräsmatta med plats för studsmatta, odlingar eller liknande på baksidan. Carport finns mittemot huset, extra p-plats och separat förråd. Här bor du nära både buss, förskola/skola, natur och flertalet stormarknader!\r\n",
                            RoomCount = 4,
                            StartingPrice = 2230000
                        },
                        new
                        {
                            ResidenceId = 5,
                            Address = "Östra Hamngatan 3",
                            BiArea = 50,
                            CategoryId = 3,
                            ConstructionYear = 1972,
                            LandArea = 200,
                            LivingArea = 120,
                            MonthlyFee = 3750,
                            OperatingCost = 20500,
                            PictureListURL = "[\"https://bilder.hemnet.se/images/1024x/12/f5/12f553af156dc9976c7b017c52e579d9.jpg\",\"https://bilder.hemnet.se/images/1024x/18/5b/185b2966fb0ada2fb03f989fe9c45a22.jpg\",\"https://bilder.hemnet.se/images/1024x/a8/92/a89266955a44d70df2fe4a76651af4e1.jpg\",\"https://bilder.hemnet.se/images/1024x/73/fe/73fe58e7f6e8db52a07f9b224fa7ca08.jpg\"]",
                            RealtorId = "ac31313d-d278-43d9-a72d-39fc96dc2e92",
                            RegionId = 5,
                            ResidenceDescription = "Sällsynt tillfälle att bli ägare till detta utmärkt planerade gavelradhus i två plan om ca 160 kvm i ett av Luthagens/Stabbys mest eftertraktade kvarter. Det här är ett perfekt hem för den växande familjen, med närhet till utmärkta förskolor och skolor i ett tryggt och barnvänligt område.\r\n\r\n\r\n\r\nRadhuset erbjuder rymlig hall som leder dig till ett ljust och luftigt vardagsrum med gott om ljusinsläpp genom de generösa fönstren. Ett funktionellt vinkelkök med stor matplats är perfekt för familjemiddagar. Uteplatser både på framsidan och baksidan ger dig möjlighet att njuta av solen från morgon till kväll. Huset rymmer totalt fem sovrum, varav två praktiskt placerade på entréplanet och tre på övre våningen. Master bedroom har dessutom en egen balkong där du kan njuta av ditt morgonkaffe. Ett stort allrum ger extra utrymme för familjens aktiviteter och kan enkelt omvandlas till ytterligare sovrum om så önskas. Dessutom finns två renoverade badrum för familjens bekvämlighet.\r\n\r\n\r\n\r\nUteplatsen på framsidan bjuder in till avkopplande stunder i eftermiddags- och kvällssolen, medan baksidans altan ger dig möjlighet att njuta av frukosten i solens första strålar. Den trevliga trädgården är perfekt för lek och rekreation, med gräsyta och fruktträd som ger trädgården extra charm. Du kommer att älska det trivsamma och omtyckta området med närhet till skogspromenader som ger glädje året runt, inklusive möjligheter till löprundor och skidåkning. Service som vårdcentral, restauranger, café och gym finns bara några kvarter bort vid Mimmi Ekholms plats. Närhet till förskolor och skolor gör vardagen smidig för hela familjen. Det här är verkligen ett hem som erbjuder både komfort och livskvalitet. Missa inte chansen att bli ägare till detta fantastiska radhus och skapa ditt drömboende för din familj.",
                            RoomCount = 5,
                            StartingPrice = 1400000
                        },
                        new
                        {
                            ResidenceId = 6,
                            Address = "Kemigränd 12",
                            BiArea = 10,
                            CategoryId = 2,
                            ConstructionYear = 1998,
                            LandArea = 0,
                            LivingArea = 90,
                            MonthlyFee = 5200,
                            OperatingCost = 32000,
                            PictureListURL = "[\"https://www.maklarringen.se/contentassets/41cd42b001da48209ba3f20452da0e63/objektbilder/fasad?preset=ObjectImageListLarge\"]",
                            RealtorId = "e8411d7f-4c81-4e1a-92fc-1890db0e5b81",
                            RegionId = 2,
                            ResidenceDescription = "Varmt välkomna till denna smakfulla och genomtänkta bostad placerad på ett idealiskt centrumnära läge. Med en kort promenad till stationsområdet är man alltid nära citys puls samtidigt som naturen är nära tack vare Bokhultets naturreservat och Växjösjön. Lägenhetens väl genomtänkta färg- och materialval genomsyrar hela bostaden och skapar en harmonisk och hemtrevlig känsla.\r\n\r\nHär erbjuds en bostad med välplanerad planlösning med öppna och sociala ytor som skapar rum för familj och vänner. Det generösa vardagsrummet har en öppen planlösning mot det stilrena köket och den trivsamma matplatsen. Vardagsrum och kök bildar tillsammans boendets hjärta. Från vardagsrummet når ni den väl tilltagna balkongen där man kan skapa sin egna gröna oas. Lägenhetens två sovrum erbjuder gott om plats både för säng och övrigt möblemang. Det helkaklade badrummet är rymligt och erbjuder en duschhörna. Här finns även en välutrustad tvätthörna med både tvättmaskin, torktumlare, arbetsbänk samt skåpsförvaring.",
                            RoomCount = 4,
                            StartingPrice = 2100000
                        },
                        new
                        {
                            ResidenceId = 7,
                            Address = "Västra Grodgatan 2",
                            BiArea = 20,
                            CategoryId = 1,
                            ConstructionYear = 2017,
                            LandArea = 200,
                            LivingArea = 240,
                            MonthlyFee = 3750,
                            OperatingCost = 50000,
                            PictureListURL = "[\"https://assets-global.website-files.com/5fd75a3e2aa1abd3e9c84632/65cfb27503791a7b1edb8b3c_grand-villa-5-sterne-hotel-villa-contessa.webp\"]",
                            RealtorId = "ac31313d-d278-43d9-a72d-39fc96dc2e92",
                            RegionId = 5,
                            ResidenceDescription = "Välkommen till detta fantastiska 1,5-planshus som ligger på en perfekt trädgårdstomt. Huset är noggrant planerat för att erbjuda både elegans och bekvämlighet. Du välkomnas av en praktisk entré med goda förvaringsmöjligheter. Det rymliga vardagsrummet har stora fönster som släpper in naturligt ljus och ger en fantastisk utsikt över trädgården. Det öppna köket är utrustat med toppmoderna apparater och generösa bänkytor, perfekt för både matlagning och socialt umgänge. på övre plan hittar vi ytterligare två sovrum och ett gemensamt badrum. Det finns även ett flexibelt utrymme som kan användas som kontor, bibliotek eller lekrum. Sovrummen på entréplanet är generösa och smakfullt inredda. Master bedroom har en egen utgång direkt till poolområdet. På baksidan av huset sträcker sig en soldränkt altan, perfekt för avkoppling och underhållning. Här finns gott om plats för utemöbler, en grillplats och en loungehörna. Altanen blickar ut över den välskötta trädgården och den inbjudande poolen.",
                            RoomCount = 6,
                            StartingPrice = 1800000
                        },
                        new
                        {
                            ResidenceId = 8,
                            Address = "Biskopägen 23",
                            BiArea = 0,
                            CategoryId = 3,
                            ConstructionYear = 2002,
                            LandArea = 40,
                            LivingArea = 120,
                            MonthlyFee = 3750,
                            OperatingCost = 20500,
                            PictureListURL = "[\"https://tengbom.se/app/uploads/2017/03/07721-2000x1440.jpg\"]",
                            RealtorId = "60205c1a-ef79-44ac-89b2-ac75176e3408",
                            RegionId = 3,
                            ResidenceDescription = "Nu har vi äntligen nöjet att presentera ett välrenoverat radhus om hela 125,5 kvm med en av de bästa hörntomterna i området. Bostaden har en öppen planlösning på entréplan, två badrum, separat tvättstuga samt fyra sovrum som samtliga är belägna på övre plan. Till höjdpunkterna hör dessutom en baksida med kvällssol. På baksidan finns ett inglasat uterum, trädäck samt stor trädgård med odlingsmöjligheter samt tre utvändiga förråd. 13 478 kr i inre reparationsfonden. Garage i länga som tillhör bostaden.\r\n\r\nHär bor du med närhet till bland annat skola, lekparker och en närbutik. För pendlaren är det endast 22 minuter in till Örebro och 10 min till Hallsberg. Ett perfekt boende för barnfamiljen!",
                            RoomCount = 4,
                            StartingPrice = 1400000
                        },
                        new
                        {
                            ResidenceId = 9,
                            Address = "Teknologigatan 32",
                            BiArea = 55,
                            CategoryId = 4,
                            ConstructionYear = 2000,
                            LandArea = 100,
                            LivingArea = 50,
                            MonthlyFee = 14000,
                            OperatingCost = 10000,
                            PictureListURL = "[\"https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_760,h_500/https://www.borohus.se/wp-content/uploads/2022/04/1800x1300_forsta-tunet-760x500.jpg\"]",
                            RealtorId = "3869a014-937b-4970-9021-3bb704bb10a2",
                            RegionId = 1,
                            ResidenceDescription = "Välkommen till detta charmiga fritidshushus om 33 kvadratmeter! Fridfullt och lugnt läge i växande Börtnäsheden.\r\nBostaden erbjuder välplanerade ytor med praktiskt kök, gott om förvaringsmöjligheter och fint ljusinsläpp. Vidare finns ett rymligt allrum, plats för både mat- och soffgrupp samt en rymlig sovalkov.\r\n\r\nTill fastigheten hör även en sovstuga med utrymme för flera sovplatser eller annat möblemang. Ytterligare en byggnad finns som inrymmer, förråd, bastu, dusch samt förbränningstoalett.\r\n\r\nHär har ni en trevlig tomt om 2451 kvm, välskött gräsmatta med många soltimmar och plats för lek.\r\n",
                            RoomCount = 1,
                            StartingPrice = 1400000
                        },
                        new
                        {
                            ResidenceId = 10,
                            Address = "Aslövsgatan 3",
                            BiArea = 70,
                            CategoryId = 1,
                            ConstructionYear = 2015,
                            LandArea = 300,
                            LivingArea = 250,
                            MonthlyFee = 16000,
                            OperatingCost = 60000,
                            PictureListURL = "[\"https://static.wixstatic.com/media/d6d69b_3c2cf8100e304193bb5eed28a30db2dd~mv2.jpg/v1/fill/w_560,h_374,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/%C2%A9%20P%C3%A5l%20Ross%20Villa%20Luciani%20Grand%20DesignFasad%20Blue%20Hour.jpg\"]",
                            RealtorId = "e8411d7f-4c81-4e1a-92fc-1890db0e5b81",
                            RegionId = 4,
                            ResidenceDescription = "Här lever du bekvämt med villakänsla och med bostadsrättens trygghet och smidighet.\r\nMed uteplatser i två väderstreck är det lätt att följa både sol och skugga efter behag.\r\nFrån Kuggås strand leder strandpromenaden till Nynässerveringen med bland annat minigolf och musikkvällar. Strax där ovanför finns köpingen med den pittoreska Storgatan där butikerna ligger på rad.\r\n\r\nAlla lägenheter är byggd med den höga standard som GBJ Bygg erbjuder, till exempel parkettgolv i alla bostadsrum, fönsterbänkar i sten, helkaklade badrum samt golvvärme i hela bostaden.\r\nEgen parkeringsplats som är förberedd för att installera laddstolpe till elbilen på framsidan och på baksidan finns den stensatta uteplatsen som följer med köpet samt förrådet på cirka 10 m².",
                            RoomCount = 7,
                            StartingPrice = 1900000
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e116f8a0-bfd5-43cc-b014-4ce2a2063664",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HomeHavenAPI.Models.Realtor", b =>
                {
                    b.HasOne("HomeHavenAPI.Models.RealtorFirm", "MyRealtorFirm")
                        .WithMany()
                        .HasForeignKey("RealtorFirmId");

                    b.Navigation("MyRealtorFirm");
                });

            modelBuilder.Entity("HomeHavenAPI.Models.Residence", b =>
                {
                    b.HasOne("HomeHavenAPI.Models.Category", "ResidenceCategory")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHavenAPI.Models.Realtor", "ResidenceRealtor")
                        .WithMany()
                        .HasForeignKey("RealtorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHavenAPI.Models.Region", "ResidenceRegion")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidenceCategory");

                    b.Navigation("ResidenceRealtor");

                    b.Navigation("ResidenceRegion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HomeHavenAPI.Models.Realtor", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HomeHavenAPI.Models.Realtor", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHavenAPI.Models.Realtor", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HomeHavenAPI.Models.Realtor", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
